Removetscheck
HubSpot/hadoop pull request #56
Opened 2024-08-05 15:02 UTC by vinayvija

When using s3 as Hadoop File system we enconter resource changed on src file system error. The reason I think is that in S3 implementation file timestamps are changed which does not happen in HDFS. [Timestamp doc](https://hadoop.apache.org/docs/current//hadoop-project-dist/hadoop-common/FileSystemShell.html#Timestamps)

Tested this by deploying this branch in QA NA. The same jobs that failed with this error passed after this change. 

Example error log

```
Application application_1722669525346_0001 failed 5 times due to AM Container for appattempt_1722669525346_0001_000005 exited with exitCode: -1000
Failing this attempt.Diagnostics: [2024-08-05 14:41:43.796]Resource s3a://hubspot-hadoop-fs-backfill-s3-h3-eu1-qa/mapred/staging/backfill-s3-h3-qa/Wkd60q0QYAePuklPUXszbRFkLCjyB03P/.staging/job_1722669525346_0001/libjars changed on src filesystem - expected: "2024-08-05T14:39:39.188+0000", was: "2024-08-05T14:41:43.775+0000", current time: "2024-08-05T14:41:43.775+0000"
java.io.IOException: Resource s3a://hubspot-hadoop-fs-backfill-s3-h3-eu1-qa/mapred/staging/backfill-s3-h3-qa/Wkd60q0QYAePuklPUXszbRFkLCjyB03P/.staging/job_1722669525346_0001/libjars changed on src filesystem - expected: "2024-08-05T14:39:39.188+0000", was: "2024-08-05T14:41:43.775+0000", current time: "2024-08-05T14:41:43.775+0000"
at org.apache.hadoop.yarn.util.FSDownload.verifyAndCopy(FSDownload.java:282)
at org.apache.hadoop.yarn.util.FSDownload.access$000(FSDownload.java:72)
at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:425)
at org.apache.hadoop.yarn.util.FSDownload$2.run(FSDownload.java:422)
```

2024-08-07 15:27 UTC, ddelong requested changes

2024-08-07 15:27 UTC, ddelong commented on hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/java/org/apache/hadoop/yarn/util/FSDownload.java
> -      throw new IOException("Resource " + sCopy + " changed on src filesystem" +
We talked about this briefly, but outright disabling this check makes me uneasy. it's there for a reason and we might start introducing unknown behavior by allowing this. S3 does work differently here, but we should make the logic reflect that fact or find a way to make modification time work as expected.

2024-08-08 17:47 UTC, johnnysohn commented on hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/java/org/apache/hadoop/yarn/util/FSDownload.java
> -      throw new IOException("Resource " + sCopy + " changed on src filesystem" +
I think the reason it's there is that it's using timestamp as a mechanism for checking if we have the right jar is in place to run the job and not something else has overwritten.

So if we get rid of timestamp check and instead do checksum comparison it would work better.

2024-08-15 09:07 UTC, vinayvija commented on hadoop-yarn-project/hadoop-yarn/hadoop-yarn-common/src/main/java/org/apache/hadoop/yarn/util/FSDownload.java
> -      throw new IOException("Resource " + sCopy + " changed on src filesystem" +
I added a check for skipping this check for s3 file systems. Looking at some [stack overflow threads](https://stackoverflow.com/questions/58300578/how-to-fix-resource-changed-on-src-filesystem-issue) they seem to safe.

2024-08-16 15:17 UTC, vinayvija commented
Tested this in NA QA backfill-s3 cluster job ran fine.

2024-08-16 15:27 UTC, ddelong approved these changes
This is safer and we can go with this.

2024-08-19 18:32 UTC, merged